[general]
import = [
    "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
opacity = 0.8
blur = true
padding = {x = 2, y = 2}
dynamic_padding = true
decorations = "Buttonless"
option_as_alt = "Onlyleft"

[font]
normal = {family = "JetBrainsMonoNL Nerd Font Mono", style = "Regular"}
size = 11
bold = {family = "JetBrainsMonoNL Nerd Font Mono", style = "Bold"}
