alias na='nvim ~/.config/zsh/aliases.zsh'
alias nz='nvim ~/.config/zsh/.zshrc'
alias nn='nvim ~/.config/nvim/init.vim'
alias nbs='nvim ~/.config/bspwm/bspwmrc'
alias ns='nvim ~/.config/sxhkd/sxhkdrc'
alias nx='nvim ~/.xinitrc'
alias np='nvim ~/.config/nvim/lua/user/plugins.lua'
alias n='nvim'
alias l='lvim'
alias ls='ls --color=auto'
alias ll='ls -l --color=auto'
alias ffrec='~/.scripts/record.sh'
alias wp='feh --bg-fill --randomize ~/Pictures/Wallpapers'
alias make50='make CC=clang CFLAGS="-fsanitize=signed-integer-overflow -fsanitize=undefined -ggdb3 -O0 -std=c11 -Wall -Werror -Wextra -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wshadow" LDLIBS="-lcrypt -lcs50 -lm"'
