alias na='nvim ~/.config/zsh/aliases.zsh'
alias nz='nvim ~/.config/zsh/.zshrc'
alias nn='nvim ~/.config/nvim/init.vim'
alias nbs='nvim ~/.config/bspwm/bspwmrc'
alias ns='nvim ~/.config/sxhkd/sxhkdrc'
alias nx='nvim ~/.xinitrc'
alias m3='sudo mount /dev/sda3 /home/saumitra/Partitions'
alias um3='sudo umount /dev/sda3'
alias n='nvim'
alias ls='ls --color=auto'
alias ll='ls -l --color=auto'
alias ffrec='~/.scripts/record.sh'
alias npo=''