#! /bin/sh

picom -b &
feh --bg-scale --randomize /home/saumitra/Pictures/Wallpapers &
$HOME/.config/polybar/launch.sh
# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# dex -a -s ~/.config/autostart/
warpd &
mpDris2 &
clipmenud &

# Mouse, Trackpad & Keyboard
xmodmap -e 'keycode 172=' &
xsetroot -cursor_name left_ptr
xinput disable 'Synaptics TM3336-001' &
xinput --set-prop 'Logitech Gaming Mouse G402' 'libinput Accel Profile Enabled' 0, 1 &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Chromium desktop='^2'
bspc rule -a spotify desktop='^3'
bspc rule -a discord desktop='^4'
bspc rule -a Screenkey manage=off
