#! /bin/sh

if xrandr | grep "HDMI-1-0 connected" &> /dev/null; then
    xrandr --output eDP --primary --mode 1920x1080 --rotate normal --output HDMI-1-0 --mode 2560x1080 --rate 100.00 --rotate normal --left-of eDP
    bspc monitor eDP -d 1 2 3 4 5
    bspc monitor HDMI-1-0 -d 6 7 8 9 10
else
    bspc monitor -d 1 2 3 4 5 6 7 8 9 10
fi

picom -b &
feh --bg-fill --randomize /home/saumitra/Pictures/Wallpapers &
$HOME/.config/polybar/launch.sh
# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
#dex -a -s ~/.config/autostart/
#warpd &
#mpDris2 &
#clipmenud &
#emacs --daemon &

# Mouse, Trackpad & Keyboard
xsetroot -cursor_name left_ptr &
# xinput disable 'ELAN1200:00 04F3:30BA Touchpad' &
xinput --set-prop 'ELAN1200:00 04F3:30BA Touchpad' 'libinput Tapping Enabled' 1 &
xinput --set-prop 'Logitech Gaming Mouse G402' 'libinput Accel Profile Enabled' 0, 1 &

pgrep -x sxhkd > /dev/null || sxhkd &


bspc config border_width         0
bspc config window_gap           2

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Emacs state=tiled
bspc rule -a Chromium desktop='^1'
bspc rule -a spotify desktop='^3'
bspc rule -a discord desktop='^4'
bspc rule -a Screenkey manage=off
