vim.opt.relativenumber = true
vim.opt.clipboard = 'unnamedplus'
vim.opt.linebreak = true
vim.opt.mouse = 'a'
vim.opt.termguicolors = true
vim.opt.signcolumn = 'yes'
vim.opt.softtabstop = 4
vim.opt.tabstop = 4
vim.opt.shiftwidth = 4
vim.opt.scrolloff = 2
vim.opt.splitright = true
vim.opt.splitbelow = true
vim.opt.showmode = false
vim.opt.hlsearch = false
vim.opt.background = 'dark'
-- vim.opt.showtabline = 2
